# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 17eebb57e332172a0548e3c739bea4a57bdee10fad07f1090485a18c8ac6c1469e7b565f57abc2f656f2aeae17d00a6582e98b5a91d22f81a74e5376c7e66bde

test:
  secret_key_base: 6a604ba12ace186db01faab062272d68f3085c34e5d011cf868d87863d2bb4732465e2941b1ad8ce7892b3ed6c1d4f5377f7c80fcf7d037e17a248cbb729f093

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
